#!/bin/sh


NAME="Domoticz-Google-Assistant"
INSTALL_DIR="$(realpath $(dirname ${BASH_SOURCE[0]}))"
PID_FILE="var/run/dzga.pid"
LOG_FILE="$INSTALL_DIR/dzga.log"

start_daemon ()
{	
	source ${INSTALL_DIR}/${NAME}/env/bin/activate
	nohup python3 ${INSTALL_DIR}/${NAME} > ${LOG_FILE} &
	# echo $! > ${PID_FILE}
	sleep 10
}

stop_daemon ()
{
    # kill `cat ${PID_FILE}`
    wait_for_status 1 10 || kill -9 `cat ${PID_FILE}`
    rm -f ${PID_FILE}
}

daemon_status ()
{
	if [ -f ${PID_FILE} ] && kill -0 `cat ${PID_FILE}` > /dev/null 2>&1; then
    # if [ -f ${PID_FILE} ]; then
        return
    fi
    rm -f ${PID_FILE}
    return 1
}

wait_for_status ()
{
    counter=$2
    while [ ${counter} -gt 0 ]; do
        daemon_status
        [ $? -eq $1 ] && return
        let counter=counter-1
        sleep 1
    done
    return 1
}

case $1 in
    start)
		if daemon_status; then
			echo ""
			echo ${NAME} is already running
			echo ""
			exit 0
		else
			echo ""
			echo Starts ${NAME} in moment ...
			echo ""
			start_daemon
			echo ""
			echo ${NAME} is now running ...
			echo ""
			exit $?
		fi
        ;;
    stop)
		if daemon_status; then
			echo ""
			echo Stops ${NAME} in moment ...
			echo ""
			stop_daemon
			exit $?
		else	
			echo ""
			echo ${NAME} is not running
			echo ""
			exit 0
		fi
        ;;
	restart)
        if daemon_status; then
			echo ""
            echo Stopping ${NAME} ...
			echo ""
            stop_daemon
			echo ""
            echo Starting ${NAME} ...
			echo ""
            start_daemon
			echo ""
			echo ${NAME} is restarted ...
			echo ""
            exit $?
        else
            echo ${NAME} is Not running
			echo ""
            echo Starting ${NAME} ...
			echo ""
            start_daemon
			echo ""
			echo ${NAME} is now running ...
			echo ""
            exit $?
        fi
        ;;
	status)
        if daemon_status; then
			echo ""
            echo ${NAME} is running
			echo ""
            exit 0
        else
			echo ""
            echo ${NAME} is Not running
			echo ""
            exit 1
        fi
        ;;
	*)
        exit 1
        ;;
esac

