name: Publish Docker Image

on:
  pull_request:
    branches: [ "beta" ]
    types:
      - closed
jobs:
  publish-docker-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/${{secrets.DOCKER_USER}}/domoticz-google-assistant:beta
        docker push ghcr.io/${{secrets.DOCKER_USER}}/domoticz-google-assistant:beta
